baseURL: https://patrick-portfolioo.netlify.app/
languageCode: en-us
title: Patrick portfolio website?
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      #A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      #AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Patrick, this is a test for a portfolio website - we'll see what happens!!!! :)
  blog: {}
  contact:
    address:
      - city: Tokyo, ST 00000
        country: Japan
        street: High Street
        title: N16
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: patrickcook81@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: #(000) 000-0000 x1234
        title: #Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: LBBS
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com/elonmusk
      - icon: fa-facebook
        label: Facebook
        url: #https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: #https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: #https://www.github.com
      - icon: fa-linkedin
        label: LinkedIn
        url: #https://www.linkedin.com
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: #Generic Blog
        url: #blogs/ipsum
      - name: #Elements
        url: #elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Ipsum Dolor Sit Amet (slightly less big one)
        title: Big One!
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: Get someone to throw it at you!
        title: What's the easiest way to catch a fish?
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Because their horns don't work!
        title: Why do cows have bells?
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Finding half a worm!
        title: What's worse than finding a worm in your apple?
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Put it out man!
        title: What do you do if you see a fire man?
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Because 7 ate 9!
        title: Why was 6 afraid of 7?
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
markup: 
  goldmark: 
    renderer: 
      unsafe: true